# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gradient.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(820, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(200,200,200);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 200, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 200, 51, 22))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 200, 16, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.color_1 = QtWidgets.QLabel(self.centralwidget)
        self.color_1.setGeometry(QtCore.QRect(0, 200, 80, 80))
        self.color_1.setStyleSheet("background-color: rgb(0,0,0,);")
        self.color_1.setText("")
        self.color_1.setObjectName("color_1")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(100, 230, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 230, 16, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 230, 51, 22))
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(100, 260, 160, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 260, 16, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 260, 51, 22))
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 230, 16, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.color_2 = QtWidgets.QLabel(self.centralwidget)
        self.color_2.setGeometry(QtCore.QRect(470, 200, 80, 80))
        self.color_2.setStyleSheet("background-color: rgb(0,0,0,);")
        self.color_2.setText("")
        self.color_2.setObjectName("color_2")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(560, 230, 160, 22))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(560, 260, 160, 22))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(760, 260, 51, 22))
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(560, 200, 160, 22))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(760, 230, 51, 22))
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(740, 200, 16, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(740, 260, 16, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(760, 200, 51, 22))
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.Taiwan))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(408, 200, 20, 81))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_displaty_color = QtWidgets.QLabel(self.centralwidget)
        self.label_displaty_color.setGeometry(QtCore.QRect(250, 50, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_displaty_color.setFont(font)
        self.label_displaty_color.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_displaty_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_displaty_color.setObjectName("label_displaty_color")
        self.label_show_01 = QtWidgets.QLabel(self.centralwidget)
        self.label_show_01.setGeometry(QtCore.QRect(30, 170, 21, 21))
        self.label_show_01.setObjectName("label_show_01")
        self.label_show_02 = QtWidgets.QLabel(self.centralwidget)
        self.label_show_02.setGeometry(QtCore.QRect(500, 170, 21, 21))
        self.label_show_02.setObjectName("label_show_02")
        self.groupBox_word = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_word.setGeometry(QtCore.QRect(620, 40, 171, 101))
        self.groupBox_word.setObjectName("groupBox_word")
        self.label_content = QtWidgets.QLabel(self.groupBox_word)
        self.label_content.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_content.setFont(font)
        self.label_content.setObjectName("label_content")
        self.lineEdit_content = QtWidgets.QLineEdit(self.groupBox_word)
        self.lineEdit_content.setGeometry(QtCore.QRect(80, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_content.setFont(font)
        self.lineEdit_content.setObjectName("lineEdit_content")
        self.label_color = QtWidgets.QLabel(self.groupBox_word)
        self.label_color.setGeometry(QtCore.QRect(10, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_color.setFont(font)
        self.label_color.setObjectName("label_color")
        self.button_word_color = QtWidgets.QPushButton(self.groupBox_word)
        self.button_word_color.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.button_word_color.setText("")
        self.button_word_color.setObjectName("button_word_color")
        self.menubar = QtWidgets.QLabel(self.centralwidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: \n"
"qlineargradient(\n"
"spread: pad, x1:0.5, y1:0, x2:0.5, y2:1,\n"
"stop:0 rgb(150, 150, 150),\n"
"stop:1 rgb(65, 65, 65))")
        self.menubar.setObjectName("menubar")
        self.groupBox_background = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_background.setGeometry(QtCore.QRect(50, 40, 171, 101))
        self.groupBox_background.setObjectName("groupBox_background")
        self.label_gradient = QtWidgets.QLabel(self.groupBox_background)
        self.label_gradient.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_gradient.setFont(font)
        self.label_gradient.setObjectName("label_gradient")
        self.label_background_color = QtWidgets.QLabel(self.groupBox_background)
        self.label_background_color.setGeometry(QtCore.QRect(10, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_background_color.setFont(font)
        self.label_background_color.setObjectName("label_background_color")
        self.button_background_color = QtWidgets.QPushButton(self.groupBox_background)
        self.button_background_color.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.button_background_color.setText("")
        self.button_background_color.setObjectName("button_background_color")
        self.checkBox_gradient_point = QtWidgets.QCheckBox(self.groupBox_background)
        self.checkBox_gradient_point.setGeometry(QtCore.QRect(90, 20, 31, 31))
        self.checkBox_gradient_point.setText("")
        self.checkBox_gradient_point.setChecked(True)
        self.checkBox_gradient_point.setObjectName("checkBox_gradient_point")
        self.button_minimun = QtWidgets.QPushButton(self.centralwidget)
        self.button_minimun.setGeometry(QtCore.QRect(740, 0, 41, 31))
        self.button_minimun.setStyleSheet("background-color: rgba(255,255,255, 0.5)")
        self.button_minimun.setText("")
        self.button_minimun.setObjectName("button_minimun")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(780, 0, 41, 31))
        self.button_exit.setStyleSheet("background-color: rgba(255,20,20, 0.7)")
        self.button_exit.setText("")
        self.button_exit.setObjectName("button_exit")
        self.label_show_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_show_2.setGeometry(QtCore.QRect(250, 50, 15, 15))
        self.label_show_2.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: rgb(255, 255, 255);")
        self.label_show_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_2.setObjectName("label_show_2")
        self.label_show_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_show_3.setGeometry(QtCore.QRect(575, 115, 15, 15))
        self.label_show_3.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: rgb(255, 255, 255);")
        self.label_show_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_3.setObjectName("label_show_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "R"))
        self.label_3.setText(_translate("MainWindow", "G"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "B"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "G"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "R"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.lineEdit_6.setText(_translate("MainWindow", "0"))
        self.label_displaty_color.setText(_translate("MainWindow", "TEST"))
        self.label_show_01.setText(_translate("MainWindow", "①"))
        self.label_show_02.setText(_translate("MainWindow", "②"))
        self.groupBox_word.setTitle(_translate("MainWindow", "Word"))
        self.label_content.setText(_translate("MainWindow", "Content:"))
        self.lineEdit_content.setText(_translate("MainWindow", "TEST"))
        self.label_color.setText(_translate("MainWindow", "Color:"))
        self.menubar.setText(_translate("MainWindow", "Gradient Color Emulator"))
        self.groupBox_background.setTitle(_translate("MainWindow", "Background"))
        self.label_gradient.setText(_translate("MainWindow", "Gradient:"))
        self.label_background_color.setText(_translate("MainWindow", "Color:"))
        self.label_show_2.setText(_translate("MainWindow", "①"))
        self.label_show_3.setText(_translate("MainWindow", "②"))
